FROM lyseontech/node:v10.6.0

RUN yarn global add --quiet\
 @vue/cli@3.0.0-rc.3\
 @vue/cli-init@3.0.0-rc.3\
# @vue/cli-overlay@3.0.0-rc.3\
# @vue/cli-plugin-babel@3.0.0-rc.3\
# @vue/cli-plugin-e2e-cypress@3.0.0-rc.3\
# @vue/cli-plugin-e2e-nightwatch@3.0.0-rc.3\
# @vue/cli-plugin-eslint@3.0.0-rc.3\
# @vue/cli-plugin-pwa@3.0.0-rc.3\
# @vue/cli-plugin-typescript@3.0.0-rc.3\
# @vue/cli-plugin-unit-jest@3.0.0-rc.3\
# @vue/cli-plugin-unit-mocha@3.0.0-rc.3\
# @vue/cli-service@3.0.0-rc.3\
# @vue/cli-service-global@3.0.0-rc.3\
# @vue/cli-shared-utils@3.0.0-rc.3\
# @vue/cli-test-utils@3.0.0-rc.3\
# @vue/cli-ui@3.0.0-rc.3\
# @vue/cli-ui-addon-webpack@3.0.0-rc.3
