FROM webdevops/php-apache-dev:7.3

# DOCUMENT_ROOT=/app
# APPLICATION_PATH=/app
# CONTAINER_UID=application
# APPLICATION_USER=application
# APPLICATION_GROUP=application
# APPLICATION_UID=1000
# APPLICATION_GID=1000

WORKDIR "/var/www/app"
